name: codegen-ci

on:
  push:
    branches: [ main, feat/sra-identity-auth ]
  pull_request:
    branches: [ main, feat/sra-identity-auth ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Java ${{ matrix.java }}
    strategy: 
      matrix:
        java: [17]

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'corretto'
      
      - name: build and publish smithy-typescript
        run: |
          git clone --depth 1 https://github.com/awslabs/smithy-typescript.git
          cd smithy-typescript
          ./gradlew clean build publishToMavenLocal
          cd ..
      
      - name: build and test codegen
        run: |
          cd ./codegen
          ./gradlew clean smithy-aws-typescript-codegen:build protocol-test-codegen:build -Plog-tests
